# Generated by Django 3.1.5 on 2021-01-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=6)),
                ('channel', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=4096)),
            ],
        ),
    ]
