# Generated by Django 3.1.5 on 2021-01-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='blank', max_length=256),
            preserve_default=False,
        ),
    ]
